---
abstract: 'expand %(foo) codes in strings'
author:
  - 'Paul Hoffman <nkuitse@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Expando
requires:
  strict: 0
  vars: 0
  warnings: 0
version: 0.04
